version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_comedor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedor
      MYSQL_USER: comedor
      MYSQL_PASSWORD: comida
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - comedor_net

volumes:
  mysql_data:

networks:
  comedor_net:
